"sub weapons"
  --"consume fluid"
  --"bubble jars add fluid to sub weapon"
  "pickup to increass sub fluid max"
  -- "pick up to assign subweapon type"
  -- "active subweapon set to nil on death"
  "dragonfly to spawn bottles and what not"
  "more sub weapons"
    "boomerang bubble"
    "holy water equivalent"
    "iron boots (bring back the head boop)"

"Enemies"
  --"bubbled enimies"
    --"drop"
      --"fluid bottle"
      --"health"
      --"nothing"
  "More Enemies"
    "duck that jumps from pitts"
    "sign wave flying duck"
    "homing flying duck"
    "bombing duck"
    "shooting duck arching shot"
    "sliding duck"

"fix the shit gui to not be so shit"
    "more encapsulation"
    "gfx for diffrent sub weapons"
    --"gfx for bubble power bar"
"Boss fight"
  "duck wizard"
    "phase one"
      "shoots aimed shot"
      "teleports form platform to platform"
    "phase tow"
      "shoots aimed shot"
      "teleports form platform to platform"
      "summons run ducks"