"sub weapons"
  --"consume fluid"
  --"bubble jars add fluid to sub weapon"
  --"pickup to increass sub fluid max"
  -- "pick up to assign subweapon type"
  -- "active subweapon set to nil on death"
  -- "dragonfly to spawn bottles and what not"
  "more sub weapons"
    --"keep sub through stage transition, lose after death"
    "set sub energy to a sain amount after death, and on initial spawn"
    "boomerang bubble"
    "holy water equivalent"
    --"iron boots (bring back the head boop)"

"Enemies"
  --"bubbled enimies"
    --"drop"
      --"fluid bottle"
      --"health"
      --"nothing"
  "More Enemies"
    "duck that jumps from pitts"
      --"logic"
      "sprite"
    "sign wave flying duck"
      --"logic"
      "sprite"
    "homing flying duck"
      --"logic"
      "sprite"
    "bombing duck"
      "logic"
      "sprite"
    "shooting duck arching shot"
      "logic"
      "sprite"
    "sliding duck"
      "logic"
      "sprite"

"fix the shit gui to not be so shit"
    "more encapsulation"
    "gfx for diffrent sub weapons"
    --"gfx for bubble power bar"
"Boss fight"
  "duck wizard"
    -- "phase one"
      -- "shoots aimed shot"
      -- "teleports form platform to platform"
    "phase tow"
      "shoots aimed shot"
      "teleports form platform to platform"
      "summons run ducks"